# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on:
  push:
    paths:
      - "**.stories.ts"
      - "**.stories.tsx"

# List of jobs
jobs:
  build-storybook:
    # Operating System
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        working-directory: ./web
        run: |
          pnpm install --frozen-lockfile

      - name: Publish Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./web
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment PR
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ github.event.pull_request.number }}
          message: "🚀storybook: ${{ steps.chromatic.outputs.storybookUrl }}"
